### PR TITLE
Fixing depricated constants in HA 2024.1

### PR DESCRIPTION
**Pull request by ChristophCaina**
this should address issue #154

please run some tests before merging, since I do not have any victron installed so far and therefore cannot do tests,

### CODE REVIEW

**Review by blauerreiter — COMMENTED** [review]
.

**Comment by ChristophCaina** [comment]
> .

thanks... I've changed it just to be sure.
Don't understand, why this has been implemented in a second import of the constants and is never used in the code here... anyway :)... thanks for pointing it out

**Comment by blauerreiter** [comment]
HA now starts without warnings

**Comment by iot-werkstatt** [comment]
I just replaced the 3 files and can confirm that after restarting HA no more errors are showing up. Great job. Thanks.

**Review by sfstar — APPROVED** [review]
LGTM

**Pull request merged**
